### ISSUE TITLE
problem compile

### ISSUE THREAD

**Issue by sicilie** [Mamograg17/kaslo#1]
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot find "/home/nulls3/Kaslo/build/Nodawa": No such file or
  directory.

make: *** [Makefile:96: install] Error 1

**Comment by Mamograg17** [comment]
Thank you @sicilie for bringing this issue to my attention! I realized that I had forgotten to update the software name in my CMakeLists.txt file, which caused the installation error you encountered. I have now updated the file with the correct name and rebuilt the project, so the installation process should work correctly.
Thanks again for letting me know about this issue.

mamograg.

**Comment by sicilie** [comment]
Another problem(
![20230409_150118](https://user-images.githubusercontent.com/130173895/230766791-0127cefd-74f4-4114-877b-5b05eab96131.jpg)
android 12

![20230409_150045](https://user-images.githubusercontent.com/130173895/230766779-9a429175-3cca-4555-9c31-5195652e1488.jpg)

**Comment by Mamograg17** [comment]
You don't have adb installed, Kaslo uses it in order to back-up partitions, so it won't work without it.
Try to follow the instructions to install it on your distro.

**Comment by sicilie** [comment]
![Screenshot from 2023-04-09 20-32-12](https://user-images.githubusercontent.com/130173895/230782054-7cedd35a-54f1-4482-8776-b1e81f05883f.png)
= (

**Comment by Mamograg17** [comment]
/dev/block/by-name/data file doesn't exist, i corrected it to /dev/block/by-name/userdata
everything should be working now.

NOTE:taking a backup of userdata partition will take a lot of time due to its huge size, you can follow the speed in terminal.

**Comment by sicilie** [comment]
![Screenshot from 2023-04-10 16-36-32](https://user-images.githubusercontent.com/130173895/230894395-8497f2af-d83c-4c1f-a61a-b3e517beadef.png)

oh ok my internal storage max 256gb m8 
thing 400+ its not ok

**Comment by Mamograg17** [comment]
the issue has been resolved on the software side. However, we wanted to clarify that the size of the generated file is dependent on the user. Unfortunately, the program does not have a way to solve this issue.

With that said, we hope that the software is now working as expected for you. We will now close this issue. If you encounter any further issues or have any questions, please do not hesitate to open a new issue. 
Thank you.

mamograg.
